blank_issues_enabled: true
contact_links:
  - name: Enchanted Veinminer on Modrinth
    url: https://modrinth.com/datapack/enchanted-veinminer
    about: Downloads, the full description and the changelog
